name: Rust

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: "Tests, stable toolchain"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check -l
